spring:
    liquibase:
        change-log: liquibase/master.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
        hikari:
            auto-commit: false
    jpa:
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.generate_statistics: false
            hibernate.jdbc.batch_size: 25
            hibernate.order_inserts: true
            hibernate.order_updates: true
            hibernate.query.in_clause_parameter_padding: true
